### ISSUE TITLE
do not store/upload zero reports

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1000]
Warn the user and/or do not upload zip if there are no reports (handle this in the store client)
uploading no reports will change the detection statuses to fixed for all of the stored reports.

**Comment by whisperity** [comment]
> 1000th issue! 🎉

**Comment by bruntib** [comment]
I reopen this issue because we need some discussion here. The question is whether we should allow the user to store an empty report list. I think we should, but if storing an empty directory unintentionally then the detection status of the reports become "resolved" and this can't be undone.

**Comment by gyorb** [comment]
Maybe we should introduce some more sophisticated way to warn the user.
If there are too many status changes we should ask if he really want's to store the results.

**Comment by bruntib** [comment]
We have a warning on storing empty report directories:
https://github.com/Ericsson/codechecker/blob/722efba2e5f20b634e5c15f86e4e1c1c27f61060/web/client/codechecker_client/cmd/store.py#L332-L333
I think storing report directories which contain no reports is necessary, otherwise CI systems couldn't handle the case when all reports are fixed in a project.

**Comment by csordasmarton** [comment]
By the way if we analyze and empty compilation database file, the compile_cmd.json file in the report directory will not be overwritten, but we will print the following log message:
https://github.com/Ericsson/codechecker/blob/722efba2e5f20b634e5c15f86e4e1c1c27f61060/analyzer/codechecker_analyzer/cmd/analyze.py#L753-L756

As bruntib mentioned above we have a warning on store command and we want to allow the user to fix every warning.
