### ISSUE TITLE
verify if user provided a valid checker/profile name

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1030]
Check if a user provided a valid checker name (sa or tidy) and warn if there is no such checker.

**Comment by whisperity** [comment]
Does Clang throw an error if a nonexistent checker is provided and prevent analysis being run?

**Comment by Xazax-hun** [comment]
Do we want to stop the analysis due to a non-existent checker?
A warning is useful for sure.
But stopping the analysis has the following consequences:
* After a check is renamed (e.g.: moved out of alpha) the new versions of CodeChecker will no longer work with the CI loop
* The same version of CodeChecker behaves differently with different versions of Clang.  So no copy and pasting command support between different environments.  (Or the same environment but different PATH environment variable.)

**Comment by gyorb** [comment]
@whisperity if I remember it correctly clang might warn about it, but clang tidy does noting. The checker name provided by the user is not forwarded directly to the analyzer it is used as a simple regex pattern to match the available analyzer names (there might be no match, noting will be turned on/off). That is why we do not forward invalid checker names to clangsa.

@Xazax-hun yes stopping the analysis might be a bit radical, we should warn the user about it. I will update the issue description.

**Comment by dkrupp** [comment]
I agree that we should only warn for every name pattern for which there is not matching checker name

**Comment by gyorb** [comment]
With the upcoming checker profiles feature in #907, there should be a warning for the profile names too.

**Comment by bruntib** [comment]
This has been solved by now. There is a warning in case of non-existing checker names. This doesn't prevent the continuation of the analysis.
