### ISSUE TITLE
Review supported browsers

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1666]
We should review if the minimal supported browser versions are still valid:
```
Internet Explorer: version 9 or newer
Firefox: version 22.0 or newer
```
Maybe we can increment the versions for some newer releases.

**Comment by whisperity** [comment]
The webapp seems not to work with IE11. The login page works, but the product list does not load after it.

![image](https://user-images.githubusercontent.com/1969470/42693150-71726074-86ae-11e8-8d61-3c7a822d5f6e.png)

![image](https://user-images.githubusercontent.com/1969470/42693126-5fc0223a-86ae-11e8-9439-b328aa333f76.png)

The result is a blank page. Using:

![image](https://user-images.githubusercontent.com/1969470/42693189-9bec3c76-86ae-11e8-9827-80c1b0603a0a.png)

Version `11.0.65` (on Windows 10) doesn't help either, getting the same errors:

![image](https://user-images.githubusercontent.com/1969470/42693321-1bfe0016-86af-11e8-9a04-42a671c56654.png)

**Comment by csordasmarton** [comment]
@whisperity I created a patch for this which will solve this problem: #1708

**Comment by whisperity** [comment]
Thank you. However, a test should be done with these changes "merged" into a local deploy to ensure the rest of the code works. Due to this break, in IE/Edge, the page does not appear and I was unable to check the rest of CodeChecker features. If possible, it should be a single patch that fixes the current problems with compatibility, and all of them.
