### ISSUE TITLE
Blank page on Firefox (and Chromium)

### ISSUE THREAD

**Issue by beojan** [Ericsson/codechecker#1827]
**Describe the bug**
The server displays a blank page on Firefox 63 on Linux.

The error in the inspector console is:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ thrift.js:348:8
TypeError: Thrift.copyList is not a function[Learn More] report_server_types.js:1776:27
TypeError: this.headerContentNode.firstChild is null[Learn More]
```
**CodeChecker version**
6.9.0

**To Reproduce**
Steps to reproduce the behavior
1. Run `CodeChecker server`
2. Go to 'localhost:8001'
3. Blank Page

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser Firefox
 - Version 63

**Comment by csordasmarton** [comment]
Hi,

What is the version of your thrift compiler? (`thrift --version`)

**Comment by csordasmarton** [comment]
What is the distribution of your linux (Ubuntu, Arch, etc.)?

In JavaScript we use 0.9.2 version of thrift:
https://github.com/Ericsson/codechecker/blob/fe5fdd2f5c59169898cb70b1c292bf0259f46dbf/vendor_projects.json#L10

I think your problem is that you are using the latest thrift compiler (0.11.0). You can try to download the latest thrift library for JavaScript (edit [vendor_projects.json](https://github.com/Ericsson/codechecker/blob/master/vendor_projects.json) file) or by installing an older version of thrift compiler (0.9.1).

**Comment by beojan** [comment]
That'll be it. It's 0.11.0 and I had to update `requirements.py`.

**Comment by csordasmarton** [comment]
In this case please edit the [vendor_projects.json](https://github.com/Ericsson/codechecker/blob/fe5fdd2f5c59169898cb70b1c292bf0259f46dbf/vendor_projects.json#L2-L13) file too.
We didn't test CodeChecker with the latest thrift so please write us back if it works.

**Comment by reneparis** [comment]
Since the vendor_projects.json file is not available in the current master clone, I've simply updated all thrieft requirements from 0.9.1 to 0.11.0.

        modified:   web/requirements.txt
        modified:   web/requirements_py/db_pg8000/requirements.txt
        modified:   web/requirements_py/db_psycopg2/requirements.txt
        modified:   web/requirements_py/dev/requirements.txt
        modified:   web/requirements_py/osx/requirements.txt

In addition, I've updated web/server/thrief to the corresponding 0.11.0 sources (from apache). It now works with the current debian buster release (debian-10.0.0).

BTW: I'm not really into virtualenv, so if there is a easier solution let me know.

**Comment by whisperity** [comment]
(Follow-up from Gitter) @reneparis There's a file which described where to fetch external resources for the Web App here: https://github.com/Ericsson/codechecker/blob/master/web/server/vendor/Makefile#L5 I think this is the one that should also be modified.

**Comment by rpavlik** [comment]
FYI, I also found this same issue with the latest git master as well as v6.10.0 tag, on Debian Buster.
