### ISSUE TITLE
Running with Debian testing, the different version of Thrift causes an exception

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#1841]
**Describe the bug**
Running with Debian testing, the different version of Thrift causes an exception
```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 20, in <module>
    from shared.ttypes import RequestFailed
  File "/var/lib/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python2.7/gencodechecker/shared/ttypes.py", line 9, in <module>
    from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
ImportError: cannot import name TFrozenDict

```
**CodeChecker version**
Base package version          | 6.9.0                                   
Package build date            | 2019-01-05T15:30                        
Git commit ID (hash)          | c55e32be0305f0a65c621acd150e3f24ff3062a2
Git tag information           | 6.9                                     
Configuration schema          | v6.0                                    
Database schema               | v6.0                                    
Server supported API (Thrift) | 6.14                                    
Client API (Thrift)           | 6.14                                    

**To Reproduce**
Install this version of thrift
https://packages.debian.org/buster/python-thrift

On my system, the following fixed my issue:
```
--- a/requirements_py/requirements.txt
+++ b/requirements_py/requirements.txt
@@ -2,4 +2,4 @@ alembic==0.9.2
 portalocker==1.1.0
 psutil==5.2.2
 sqlalchemy==1.1.11
-thrift==0.9.1
+thrift==0.11.0

```

**Comment by gyorb** [comment]
Yes we know about the version change, we did not update the requirements yet because the newer thrift compiler is not available in Ubuntu 18.04 LTS. There was a build problem during the package sync to ubuntu which is not resolved yet. https://bugs.launchpad.net/ubuntu/+source/thrift/+bug/676486

This is a bit inconvenient but the only solution right now is to manually change the requirements for a newer version until the newer thrift compiler will be available on Ubuntu (for out automatic tests we use travis-ci with ubuntu xenial right now).
Archlinux has a newer default thrift compiler so this is an issue there too.

**Comment by sylvestre** [comment]
no worries, it is just to detail the issue for other folks impacted by this cryptic error message :)

**Comment by LebedevRI** [comment]
Looks like thrift is now in ubuntu eoan. But not in earlier versions.
I'm guessing that is still a roadblock to resolving this?

**Comment by Xazax-hun** [comment]
I think the plan is (I do not know what is the current status) to have the precompiled thrift files in the repository (as submodules) and have the thrift libraries downloaded using pip. This should circumvent the availability of thrift compiler in distros.

**Comment by LebedevRI** [comment]
To be specific, i'm in a similar boat as @sylvestre - debian sid, with thrift 0.11.0-6,
so i only need to fix the version in `requirements.txt`.


> to have the precompiled thrift files in the repository (as submodules)

Uh, hopefully those will only be used if a proper version of thrift is not found.

**Comment by gyorb** [comment]
I think we can close this issue.
Since the changes in #2570 a pypi package is created from the thrift stubs so building the CodeChecker package does not depend on the thrift compiler on the host machine.
Every required thrift library is downloaded from pypi or npmjs with the right version. A virtual environment update might be needed.
