### ISSUE TITLE
Unintended salt?

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#2118]
We end up using the connection string as a salt for the session manager. Is this intentional?

See https://github.com/Ericsson/codechecker/blob/master/web/server/codechecker_server/server.py#L950

```
        manager = session_manager.SessionManager(
            server_cfg_file,
            config_sql_server.get_connection_string(),
            root_sha,
force_auth)
```

**Comment by gyorb** [comment]
A session salt is created, but I did not found any usage of it:
https://github.com/Ericsson/codechecker/blob/97264dad474ca3232d7c841dc9c5589eccc91771/web/server/codechecker_server/session_manager.py#L174

@whisperity do you have any comments? I think we can remove it.

**Comment by whisperity** [comment]
> A session salt is created, but I did not found any usage of it:
> 
> https://github.com/Ericsson/codechecker/blob/97264dad474ca3232d7c841dc9c5589eccc91771/web/server/codechecker_server/session_manager.py#L174
> 
> @whisperity do you have any comments? I think we can remove it.

@gyorb Hah. As far as I could backtrack the blame, that was intended to provide a mechanism so that NATed clients won't accidentally bleed over between each others' session.

If this works for different clients between NAT and with a load-balanced server, I think the current code is good to go, and there is no need for that variable anymore. I can't find any use of it in the current codebase either...
