### ISSUE TITLE
A second import fails on a database error

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#218]
I am probably doing something wrong but running the command:

```
CodeChecker check --dbusername codechecker --dbport 5432 -n firefox -w ~/checker_workspace -l /home/sylvestre/checker_workspace/build.log
```

on a second run generates this error:

```
[INFO] - Parsing log file: /home/sylvestre/checker_workspace/build.log
[INFO] - Parsing log file done.
[INFO] - Checking for database
[INFO] - Waiting for check results on [40618]
[INFO] - Server error.
[INFO] - Error code: 0
[INFO] - Error message: (psycopg2.IntegrityError) ERROR:  the value of a duplicated key breaks the unique constraint « runs_name_key » [1]
DETAIL:  The key « (name)=(firefox) » already exists. [1]
 [SQL: "INSERT INTO runs (id, date, duration, name, version, command, inc_count) VALUES (nextval('run_id_seq'), %(date)s, %(duration)s, %(name)s, %(version)s, %(command)s, %(inc_count)s) RETURNING runs.id"] [parameters: {'name': 'firefox', 'duration': -1, 'inc_count': 0, 'version': '4.0', 'command': '/home/sylvestre/dev/mozilla/codechecker/codechecker_package/CodeChecker/cc_bin/CodeChecker.py check --dbusername codechecker --dbport 5432 -n firefox -w /home/sylvestre/checker_workspace -l /home/sylvestre/checker_workspace/build.log', 'date': datetime.datetime(2015, 12, 28, 16, 27, 40, 398042)}]

[1] are translated from French
```

**Comment by igalex** [comment]
CodeChecker identifies each result set with a unique name: this is what you define with the -n parameter (in this case firefox). Therefore for each "check" you should give a new unique name using the --name/-n command line parameter. Usually the run name is a combination of the application name and its version.

I see the following problems here:

1. CodeChecker should show a detailed error message when a run with the given name already exists. I think the problem here is that the current implementation of the run name uniqueness checking depends on the database server's language. It should be fixed as soon as possible! [Hint for the developers](https://github.com/Ericsson/codechecker/blob/master/codechecker_lib/arg_handler.py#L350)
2. The user guide should be more detailed about run names and its usage.
3. The command line help should be more detailed too.

**Comment by sylvestre** [comment]
Thanks for the quick feedback.

I am interested in codechecker for the feature: *incremental bug reporting (show only new bugs compared to a baseline)'*, I am trying to achieve that but I am don't see how code checker can deal with unique name here?!

**Comment by igalex** [comment]
Just add the ``--update`` flag and use the same name for each run. This is also poorly documented.

A usual incremental workflow:

1. ``CodeChecker check -n foo -w ~/foows -b 'make clean && make' `` (clean build)
2. Do some coding
3. ``CodeChecker check -n foo --update -w ~/foows -b make``
4. Repeat  2 - 3

In the incremental mode CodeChecker replaces the results for each file it checks, therefore it's important that the build system should only build the changed files in point 3, otherwise it will be slower.

**Comment by dkrupp** [comment]
Hi Sylvestre,

If you want to compare two versions of firefox for the contained bugs, you need to check the code the two different versions of the source code and give them different run names. Thenyou can compare them in the WEB GUI or in command line and show the new/resovled/unresolved bugs between the two versions.

So
1. check version 1 of firefox  `CodeChecker check -n firefox_v1 -w ~/foows -b 'make clean && make'`
2. check version 2 of firefox and call it firefox_v2 `CodeChecker check -n firefoxv2 -w ~/foows -b 'make clean && make'`
3. Then start the webserver: `CodeChecker server -w ~/foows -v 9999`
4. View the results in firefox `#firefox http://localhost:9999`
5. Or alternatively list the diff of the two runs and show new bugs in firefox version 2 in command line: ` CodeChecker cmd diff -b firefox_v1 -n firefox_v2 -p 8001 --new`

I hope this helps.
Regards,
Daniel

**Comment by gyorb** [comment]
With the new release 5.2 CodeChecker runs by default in update mode. Which means it will overwrite previous analysis results if the same run name is used. This change should fix the error in the description.
Please @sylvestre verify if you still have this error with the new release.

**Comment by gyorb** [comment]
@sylvestre did you try the latest release if this bug still exists?

**Comment by gyorb** [comment]
closed because of no feedback

**Comment by sylvestre** [comment]
@gyorb Actually, I still can reproduce with:

> CodeChecker check --dbusername codechecker_user --dbport 5432 -n firefox -w ~/checker_workspace -b "cd ~/dev/mozilla/ff/mozilla-inbound &&  hg pull -u && hg update -r default && ./mach build"

and I am running the head of this git repo.

Using --update fixes the issue.

**Comment by gyorb** [comment]
If you want to use PostgreSQL database you should use the --postgresql option in the command line. In the latest versions the default database backend is SQLite which will create an SQLite database in the codechecker workspace directory automatically.
Please cleanup everything (codechecker repository, codechecker workspace, database) and try to rebuild the CodeChecker package from scratch and use the master branch.
If it still does not work enable debug mode (export CODECHECKER_VERBOSE=debug)
and send us the log, it should give us more information.

**Comment by gyorb** [comment]
Do you still get this error message?

**Comment by gyorb** [comment]
@sylvestre do you still get this error with the latest release?

**Comment by sylvestre** [comment]
Nope, I havent seen it for a while, thanks
