### ISSUE TITLE
CodeChecker store fails to process analysis, crashes with Error -5 while decompressing data: incomplete or truncated stream', extraInfo=None

### ISSUE THREAD

**Issue by kenroser** [Ericsson/codechecker#2826]
**Describe the bug**
I can successfully analyze and parse my results.  My problem begins when I try to use the server and store the results.  The store process aborts with errors.  See attached file

**CodeChecker version**

CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version
---------------------------------------------------------------
Base package version | 6.13.0
Package build date   | 2020-07-08T17:44
Git commit ID (hash) | db517a98b095a8a03c6e3a551e8b5943844e1f84
Git tag information  | 6.13
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version
------------------------------------------------------------------------
Base package version          | 6.13.0
Package build date            | 2020-07-08T17:44
Git commit ID (hash)          | db517a98b095a8a03c6e3a551e8b5943844e1f84
Git tag information           | 6.13
Server supported API (Thrift) | 6.28
Client API (Thrift)           | 6.28
------------------------------------------------------------------------

**To Reproduce**
CodeChecker store ./reports  --name uu --url http://ramapo.wi.direct.com:61511/Default

**Expected behaviour**
No crash

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: Firefox

**Additional context**
[output.txt](https://github.com/Ericsson/codechecker/files/4898116/output.txt)

**Comment by csordasmarton** [comment]
@kenroser In case of SQLite the maximum number of host parameters in a single SQL statement is set to 999 (SQLite version <= 3.32.0 /https://www.sqlite.org/limits.html/). In you case it is larger then 2000. It can be configured with the `SQLITE_MAX_VARIABLE_NUMBER` variable during compile time (https://stackoverflow.com/questions/15312590/what-is-the-limit-of-sql-variables-one-can-specify-in-a-single-execsql-query). So you have to compile your own SQLite.

For big projects it is recommended to use `PostgreSQL` database instead of SQLite.

We have docker images for the CodeChecker web server. So you can run a CodeChecker web server and a PostgreSQL server easily with docker. You can find more information and some examples in our user guide: https://github.com/Ericsson/codechecker/blob/master/docs/web/docker.md
