### ISSUE TITLE
insufficient evaluation of assumptions for null pointer checks

### ISSUE THREAD

**Issue by KristofSzabados** [Ericsson/codechecker#3098]
**Describe the bug**
Many of the null pointer checks reported for Titan.core is similar to this particular one.
The steps reported by codechecker:
"
     1, PreGenRecordOf.cc:38242:8: Calling 'PREGEN__SET__OF__HEXSTRING::replace'
     2, PreGenRecordOf.cc:36817:1: Entered call from 'PREGEN__SET__OF__HEXSTRING_template::replace'
     3, PreGenRecordOf.cc:36820:5: Assuming field 'val_ptr' is not equal to NULL
     4, PreGenRecordOf.cc:36823:1: Calling 'PREGEN__SET__OF__HEXSTRING::set_size'
     5, PreGenRecordOf.cc:36848:1: Entered call from 'PREGEN__SET__OF__HEXSTRING::replace'
     6, PreGenRecordOf.cc:36850:5: Assuming 'new_size' is >= 0
     7, PreGenRecordOf.cc:36855:1: Null pointer value stored to field 'value_elements'
     8, PreGenRecordOf.cc:36869:5: Assuming 'new_size' is <= field 'n_elements'
     9, PreGenRecordOf.cc:36823:1: Returning from 'PREGEN__SET__OF__HEXSTRING::set_size'
    10, PreGenRecordOf.cc:36824:17: Assuming 'i' is < 'index'
    11, PreGenRecordOf.cc:36824:17: Entering loop body
"

The interesting parts of the code: //with line numbers added as comment to clarify the situation.
part of "replace"
"
PREGEN__SET__OF__HEXSTRING PREGEN__SET__OF__HEXSTRING::replace(int index, int len, const PREGEN__SET__OF__HEXSTRING& repl) const //line 36817
{
if (val_ptr == NULL) TTCN_error("The first argument of replace() is an unbound value of type @PreGenRecordOf.PREGEN_SET_OF_HEXSTRING.");
if (repl.val_ptr == NULL) TTCN_error("The fourth argument of replace() is an unbound value of type @PreGenRecordOf.PREGEN_SET_OF_HEXSTRING.");
check_replace_arguments(val_ptr->n_elements, index, len, "@PreGenRecordOf.PREGEN_SET_OF_HEXSTRING","element");
PREGEN__SET__OF__HEXSTRING ret_val;
ret_val.set_size(val_ptr->n_elements + repl.val_ptr->n_elements - len); //line 36823
for (int i = 0; i < index; i++) { // line 36824
"

part of set_size:
"
void PREGEN__SET__OF__HEXSTRING::set_size(int new_size)  // line 36848
{
if (new_size < 0) TTCN_error("Internal error: Setting a negative size for a value of type @PreGenRecordOf.PREGEN_SET_OF_HEXSTRING.");
if (val_ptr == NULL) {
val_ptr = new recordof_setof_struct;
val_ptr->ref_count = 1;
val_ptr->n_elements = 0;
val_ptr->value_elements = NULL;
} else if (val_ptr->ref_count > 1) {
struct recordof_setof_struct *new_val_ptr = new recordof_setof_struct;
new_val_ptr->ref_count = 1;
new_val_ptr->n_elements = (new_size < val_ptr->n_elements) ? new_size : val_ptr->n_elements;
new_val_ptr->value_elements = (HEXSTRING**)allocate_pointers(new_val_ptr->n_elements);
for (int elem_count = 0; elem_count < new_val_ptr->n_elements; elem_count++) {
if (val_ptr->value_elements[elem_count] != NULL){
new_val_ptr->value_elements[elem_count] = new HEXSTRING(*(val_ptr->value_elements[elem_count]));
}
}
clean_up();
val_ptr = new_val_ptr;
}
if (new_size > val_ptr->n_elements) {
"

some minor background context on what the code is meant to do here:
The replace function is replacing the elements in the current "list", len elements from index, with the elements of repl.

The path through set_size indicates that:
- we are creating a new object to store the result, with initially 0 elements.
- "'new_size' is >= 0" and "'new_size' is <= field 'n_elements'" can only happen if new_size == 0, since val_ptr->n_elements is set to 0 in line 36854

In the replace function (calling site of set_size) this would mean, that set_size is called with 0 as the actual value of the parameter.
that is "val_ptr->n_elements + repl.val_ptr->n_elements - len" == 0. ( please note that this means that all elements of the initial list is replaced with a list of 0 elements )
This is a valid scenario so far.
This however also means, that the call to the function "check_replace_arguments" in replace will only succeed if idx + len <= value_length is true in its body (should we try to replace more elements then what is present will result in an error).
This means that the value of "index" in "replace" has to be 0.

At which point the assumption of "'i' is < 'index'" is invalid and the loop is not entered ... never reaching the site that could result in dereferencing a null pointer.

**CodeChecker version**
6.15

**To Reproduce**
run codechecker on our project.

**Expected behaviour**
This is quite a complex situation ... but maybe the analyzer used in codechecker could be improved to recognize such situations too ... and not report an error for them.

**Desktop (please complete the following information)**
 - OS: Win10
 - Browser: Firefox
 - Version: 83.0

**Additional context**
the project used is titan.core: https://github.com/eclipse/titan.core
The file in question is generated during build, not under version control.

**Comment by csordasmarton** [comment]
@KristofSzabados This problem is related to the static analyzers (Clang Tidy, Clang Static Analyzer) and not to the CodeChecker. Please create a ticket to the https://bugs.llvm.org/.

**Comment by ekrisza** [comment]
Please don't close valid bug reports before they are actually fixed.
Keeping bug reports for valid bugs open has several benefits:
- it can be seen when the bug was found and the developers notified of it.
- if it is administered when the bug is fixed, this will also be traceable later.
- if you also research when the bug appeared, that will also be visible.
This way external users and researchers will be able to tell in which time-intervall the reports of codecheker were unreliable/imprecise.

Right now if someone else runs into the same bug and finds this bug report closed, they might rightfully assume that the bug was fixed (as the bug report is closed).

Also I understand that the bug might be coming from some 3rd party tool codechecker depends on. Please note, that as we were using the web interface of codechecker we don't really have precise information on how your tool is using the built in 3rd party tool: what parameters they are called with, what environmental variables are set, what other arrangements codechecker might be doing.
As this information is best known by the developers of codechecker it would be best if you could write the bug report for the 3rd party tool, extending our report with all the additional information that might be needed.

Thank you in advance

**Comment by csordasmarton** [comment]
I agree that this is a valid bug report, but this is not for CodeChecker but for Clang. As you know CodeChecker only wraps analyzers such as Clang Static Analyzer and Clang Tidy, so as you wrote these are our 3rd party libraries.

In my opinion issues for a repository should contain bug reports / features requests which are related to the actual repository and can be fixed by modifying the repository source code. In your case we can't do that because we need to modify the analyzers which source code is in a separate repository and a separate team is working on them.

If everybody creates a ticket under the CodeChecker repository which are related to our 3rd party libraries, the number of open issues will drastically grow, nobody will solve these problems because we don't have enough resources and it will also mess up the issues in this repository. So it will be difficult to find real issues which are actually CodeChecker problems.

Please also keep in mind that very few people (~2) are working on the CodeChecker source code officially and we are not working on the analyzer (Clang) part too. So if you have problem for example with the web interface, the client or any other commands which were executed by the CodeChecker command you can create a new ticket under this repository and we will try to answer it / fix it.

**Comment by ekrisza** [comment]
I guess we have to accept, that Ericsson has limited resources.

That said I still believe you should leave valid bug reports open until they are fixed:
- There might be any number of researchers (and users) using this product.
   Having the bug report closed might indicate to them, that this issue was fixed and
   they do not need to pay attention to it.
   Which could corrupt any number of research efforts (that you might not know about)
- Being an open-source project, you could attract any number of external developers for open bug reports.
  This could eliminate you limited resources (2 people working on the project).

- you can also use this opportunity to give feedback to the 3rd party tools you use.
   you could for example check the still open bug reports in regularly and indicate it back to the other team
   that they still need to concentrate on it, or if it was already fixed.

Please also note, that you might already have some support contract with some companies to help you in such situations.
As far as I know it is quite common for large companies (like Ericsson) to have support contracts for such 3rd party dependencies.
Such an organization could quickly handle such issues (at least I hope)

Anyways, I just asked to get access to write bug reports to  https://bugs.llvm.org/.
As you proposed I will write a new bug for clang tidy, for this bug (also linking this bug report for context).

Thank you.

**Comment by ekrisza** [comment]
I just created the bugreport for clang-tidy at the site you recommended: https://bugs.llvm.org/show_bug.cgi?id=48620
(please note, that It might be better to have the followup communication here, to stick to a single location, without fragmenting the handling of this issue)

Also as I was using the web interface of CodeChecker ... Clang-tidy people might need some more information on how you tool is using their program.

**Comment by njames93** [comment]
> Also as I was using the web interface of CodeChecker ... Clang-tidy people might need some more information on how you tool is using their program.

Definitely not a clang-tidy problem per say, I've moved your bug report to the clang static analyzer bugs as it may get better response there.
