### ISSUE TITLE
Git blame view

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/codechecker#3135]
- CodeChecker will show for each line the date and commit of the last modification of that line. So it will be possible for a developer to check who modified the source line last where a CodeChecker error appears.
- For each report, CodeChecker will also store the date of the commit which last modified the line of code where the problem is reported. A new filter will be added to CodeChecker `Commit date after/before` which can be used to list the reports that were added in a specific time interval.

**Comment by jimis** [comment]
> For each report, CodeChecker will also store the date of the commit which last modified the line of code where the problem is reported.

+1 for this feature, I've been looking for it.

Just a heads up though, sometimes the report points to a line that was not modified recently. You have to walk up the chain of steps in the report until you find a line recently modified, and that is most likely the one responsible.

For example, a null pointer dereference might happen on a line untouched for years, because the caller function has flawed logic.
