### ISSUE TITLE
[docs]Can't open the 'Report Converter Tool' page

### ISSUE THREAD

**Issue by uhziel** [Ericsson/codechecker#3241]
**Describe the bug**

Can't open the 'Report Converter Tool' page

Can only use 'https://github.com/Ericsson/codechecker/blob/master/tools/report-converter/README.md'  to access.

![image](https://user-images.githubusercontent.com/212357/112245839-a5ce4180-8c8c-11eb-92f7-8fbe0148fc3b.png)

**To Reproduce**

1. Open https://codechecker.readthedocs.io/en/latest/
2. Find 'Report Converter Tool'
3. Click on 'Report Converter Tool'

**Comment by jay24rajput** [comment]
@csordasmarton I would like to work on this issue. Maybe you can direct me as to why the hyperlink is breaking(since it is displaying data directly from github readme links)

**Comment by csordasmarton** [comment]
@jay24rajput The documentation what you can see when you visit this link is generated by using `mkdocs`. The configuration file which describe the options how it is built can be found here:
https://github.com/Ericsson/codechecker/blob/cc64e489d064bb4dfaec49c0cae1335e60f8ea4a/mkdocs.yml#L7

Unforunately you can specify only one directory for this tool and it walk through all the files in this directory and generates this documentation. The problem is that our CodeChecker repository contains multiple "sub-modules" / tools, and the documentation can be found in different locations.

So a solution can be if we move every documentation files under the [`docs`](https://github.com/Ericsson/codechecker/tree/master/docs) directory.

For example:
```sh
|- docs
  |- analyzer
  |- web
  |- tools
    |- report_converter.md
    |- plist_to_html.md
    |- ...
```

**Comment by jay24rajput** [comment]
@csordasmarton Hmm.. but that would make its documentation messed up I think. Do you think we shift all the readme files to the folder?

I was also thinking, maybe we can issue a make command for copying all the readme files in the project to the docs directory.  Something like this:
```sh
make docs
```
It would also overwrite all the files in there exists one already

**Comment by csordasmarton** [comment]
@jay24rajput The documentation is generated automatically by the https://readthedocs.org/ page which reads the above mention configuration file from the repository. I don't think it supports custom build processes (like make) and I don't see any option for it on the Administrator page.

**Comment by jay24rajput** [comment]
@csordasmarton Ohh alright! This leaves us with no option but to shift the readme files to the docs folder right?

**Comment by csordasmarton** [comment]
@jay24rajput Unfortunately yes, I don't see any other solution for this problem now.

**Comment by jay24rajput** [comment]
Hello @csordasmarton 

In spite of the PR is merged, the readthedocs still shows 404 error (https://codechecker.readthedocs.io/docs/tools/report-converter.md#kernel-doc)
