### ISSUE TITLE
Duplicated bug report in html parser

### ISSUE THREAD

**Issue by vChavezB** [Ericsson/codechecker#3510]
**Describe the bug**
I updated a project with CI that uses a docker container with Codechecker v6.18.0  and found out that the HTML parser creates duplicated bugs. The stats show me that v6.16.0 created 47680 severities while for v6.17.0 it creates 58, for the same source files.

I noticed that duplicate notification when calling `codechecker parser` came from the file [parser.py](https://github.com/Ericsson/codechecker/blob/9f28db29804cfcd140938e9b994dd1810dafb38f/analyzer/codechecker_analyzer/cmd/parse.py) as:
```bash
[DEBUG][2021-11-18 12:44:02] {system} [1111] <139743470372672> - parse.py:861 skip_html_report_data_handler() - Skip report because it is a deduplication of an already processed report!
[DEBUG][2021-11-18 12:44:02] {system} [1111] <139743470372672> - parse.py:863 skip_html_report_data_handler() - Path hash: 4ef14c44533cd366c92c216f675b2aa1
```

 and now they come from [reports.py](https://github.com/Ericsson/codechecker/blob/9f28db29804cfcd140938e9b994dd1810dafb38f/tools/report-converter/codechecker_report_converter/report/reports.py) as:
```bash
[DEBUG][2021-11-18 11:34:20] {report-converter} [689] <140192054974272> - reports.py:118 skip() - Not showing report because it is a deduplication of an already processed report!
[DEBUG][2021-11-18 11:34:20] {report-converter} [689] <140192054974272> - reports.py:120 skip() - Path hash: b4a42a125db8720a6a2d0b5d4bc096ec
```
So it seems that the parser detects the duplicates but they are still visible in the HTML view.

**CodeChecker version**
v6.18.0

**To Reproduce**

1. Build and trace with `CodeChecker log` a project which has bugs that can be detected as duplicates. For example, a header that is included in different .cpp files.
2. Analyze and parse the report:
  ``` bash
  CodeChecker analyze codechecker.log --output ./codechecker_report --enable extreme --ctu -i skip.file -q
  CodeChecker parse --export html --output ./codechecker_html ./codechecker_report
  ```

**Expected behaviour**
Duplicate errors in html generated pages are removed

**Desktop (please complete the following information)**
 - OS: Docker container Linux debian:buster-slim

**Additional context**
The project where I found the bug is for an MCU with arm-none-eabi-gcc compiler. At the moment as a temporal solution, I will stick with v6.17.0

**Comment by whisperity** [comment]
I have just run into this issue and can confirm this is happening. We found this in the CI of [Contour-Terminal](http://github.com/contour-terminal/contour), where the PList HTML compressed ZIP artefact that we uploaded to the CI suddenly jumped from [~20 MiB](http://github.com/contour-terminal/contour/actions/runs/1417046561) in size to [400 MiB](http://github.com/contour-terminal/contour/actions/runs/1433587010). (Now it is at [**745 MiB**](http://github.com/contour-terminal/contour/actions/runs/1501257682)) The CI job we use always runs latest *`master`* CodeChecker.

Thanks to the build script of CodeChecker telling me the precise version, so far, I've been able to nail down the diff between these commits to be the culprit: https://github.com/Ericsson/codechecker/compare/9f894e3e4be032574d4e47f263b333d8a0b0fc1b...85dd52dc8f4d47fcf26419fcb44de1ff2a58924f

# A minimal example

> Thanks to @bruntib for helping in nailing this down.

## Input "project"

### `header.h`

```cpp
int s() { return sizeof(42); }
```
### `main.cpp`

```cpp
#include "header.h"

int main() { return s(); }
```

### `main2.cpp`

Same as `main.cpp`:

```cpp
#include "header.h"

int main() { return s(); }
```

# Execution

Running the analysis on the two source files results in the warnings:

~~~~
/tmp/header.hpp:1:18: warning: suspicious usage of 'sizeof(K)'; did you mean 'K'? [bugprone-sizeof-expression]
int s() { return sizeof(42); }
                 ^
~~~~

If I run this with the old version (9f894e3e4be032574d4e47f263b333d8a0b0fc1b), it's fine. With the new version (85dd52dc8f4d47fcf26419fcb44de1ff2a58924f or **v6.18.0**), every report is converted/shown multiple times.

Instead of showing **1** bug (that is located _only_ in the header!), it creates **4** bugs: main-tidy, main2-tidy, main-clangsa, main2-clangsa. For some reason, the `_clangsa` HTMLs will contain the Tidy report, even though the `_clangsa` PLists are empty!

**Comment by whisperity** [comment]
Subsequent testing boiled the culprit down to 85dd52dc8f4d47fcf26419fcb44de1ff2a58924f.

I've re-run the analysis of Contour as mentioned above to rule out the "system under test" changing, on the same content of the analysed project. This is now the results of a real project's analysis.

-  9f894e3e4be032574d4e47f263b333d8a0b0fc1b (original good commit): [17.6 MiB](http://github.com/whisperity/contour/actions/runs/1507226234), good!
- -  9f894e3e4be032574d4e47f263b333d8a0b0fc1b (original good commit): [17.6 MiB](http://github.com/whisperity/contour/actions/runs/1507226234), good!
- -  9f894e3e4be032574d4e47f263b333d8a0b0fc1b (original good commit): [17.6 MiB](http://github.com/whisperity/contour/actions/runs/1507226234), good!

**Comment by whisperity** [comment]
Subsequent testing boiled the culprit down to 85dd52dc8f4d47fcf26419fcb44de1ff2a58924f.

I've re-run the analysis of Contour as mentioned above to rule out the "system under test" changing (as it definitely did in the [23 .. 18] days ago mentioned), on the **same content** of the analysed project.

-  9f894e3e4be032574d4e47f263b333d8a0b0fc1b (original good commit): [17.6 MiB](http://github.com/whisperity/contour/actions/runs/1507226234), **good! ✔️**
-  0b78a110f5976186b778c95a8b12fd19f101b640 (the direct parent of 85dd52dc8f4d47fcf26419fcb44de1ff2a58924f): [17.4 MiB](https://github.com/whisperity/contour/actions/runs/1507409469), **good! ✔️**
-  85dd52dc8f4d47fcf26419fcb44de1ff2a58924f (the culprit, #3462): [736 MiB](http://github.com/whisperity/contour/actions/runs/1507230556), **bad!! ❌**
-  198ab833a40d2cb0c5bd02610e558922b6a57bbc (the `master` commit at the time the previous comment was written): [739 MiB](http://github.com/whisperity/contour/actions/runs/1507232959), **bad!! ❌**

**Comment by csordasmarton** [comment]
@whisperity I created a patch which I think will solve this problem: #3524. Can you please try it out?

**Comment by jimis** [comment]
I hit the same bug on HTML report generation and verify that 6.18.1 fixes it. 

But could it be that the diff command has the same bug? Check [this diff report here](https://testresults.qt.io/codechecker/daily_diffs/qtbase/dev/qtbase-dev-20211221-8678ab9354/) that mentions 180 issues, while diffing in the UI shows only 15. It was generated with `CodeChecker cmd diff -o html --new -b run1 -n run2 ...`.

Should we re-open this ticket?

**Comment by csordasmarton** [comment]
@jimis Did you use remote runs for both --baseline and --newline options (run1 + run2) or one/both of them are local report directories?

**Comment by csordasmarton** [comment]
Also one more thing. I found a problem couple of days ago that in diff mode bug steps are always 1 for remote reports because we do not get and print these information to the generated HTML files. I created a patch which will solve this problem: #3555. Can you please try it out too?

**Comment by jimis** [comment]
@csordasmarton both baseline and new are local directories. The baseline was generated with 6.18.0, the new with 6.18.1. The diff report in the UI appears normal.

About #3555 we never use plain text diff output, nor diff against "remote" reports. I'll try to see if I can reproduce the issue easily but no guarantees. If so I'll comment on #3555.

**Comment by csordasmarton** [comment]
In the source code of the diff command we filter out duplicated reports:
https://github.com/Ericsson/codechecker/blob/4c8817de6db6b4bf2cabf0e597cf8e614154086f/web/client/codechecker_client/cmd_line_client.py#L205-L206

From the link what you have sent it looks like that the reports are coming from different header/source files (see the url parameters):
These are the first 3 reports:
![image](https://user-images.githubusercontent.com/6695818/146896648-dcdc68b9-3680-413d-b543-9302af60cbb5.png)

And the links for these reports:
- [qthread.cpp](https://testresults.qt.io/codechecker/daily_diffs/qtbase/dev/qtbase-dev-20211221-8678ab9354/qthread.cpp_%2091627393.html#reportHash=90d6271a64001c343673c7b7c0e3a8eb)
- [qringbuffer_p.h](https://testresults.qt.io/codechecker/daily_diffs/qtbase/dev/qtbase-dev-20211221-8678ab9354/qringbuffer_p.h_%2030851720.html#reportHash=90d6271a64001c343673c7b7c0e3a8eb)
- [qscopedpointer.h](https://testresults.qt.io/codechecker/daily_diffs/qtbase/dev/qtbase-dev-20211221-8678ab9354/qscopedpointer.h_%2069186994.html#reportHash=90d6271a64001c343673c7b7c0e3a8eb)

Also if you open a report in the source code section you see the following warning message:
![image](https://user-images.githubusercontent.com/6695818/146896815-8497b197-845c-40d2-82f0-d0165afe13f1.png)

Please try to re-analyze your project again.

**Comment by jimis** [comment]
> [first 3 reports point to different links]

On the listing, they are listed multiple times. For example the issue in qringbuffer_p.h is the one listed at position 13. It shouldn't be listed at position 2 with "qthread.h" as title. The diff command that generated this HTML listing shows only 15 issues found:

```
----======== Summary ========----
----------------------------------------------
Number of processed analyzer result files | 0 
Number of analyzer reports                | 15
----------------------------------------------
```

> Please try to re-analyze your project again.

I'm not sure I follow. Yes it says the source code is missing, I considered this part of the bug. Re-analyze what exactly, the same checkout? And then run the same diff command? Why would that fix the issue?

FWIW the diff command we use has not changed and it used to work in 6.17, and the files (for example `src/corelib/thread/qthread.cpp`) are found where expected in the file system, under the source directory.

**Comment by jimis** [comment]
> Did you use remote runs for both --baseline and --newline options (run1 + run2) or one/both of them are local report directories?

I think I got this wrong. Even though the directories are there and have the same name as the runs, I believe we are using "remote" comparisons, since the `CodeChecker cmd diff` command contains the `--url` argument.

I tried to reproduce my issue with both the 6.18.1 version and the CodeChecker version from #3555, but it was not possible: I get a normal listing of 15 issues now. However I still get "File not found" for the source files and I'm not sure why. Maybe because the files are analysed with `--trim` and the paths not found are relative, not absolute ones.

The patched version shows one difference though, each issue shows a much deeper path length.

I will try again a few days later, after new issues start appearing again.
