### ISSUE TITLE
Responses for errorneous results

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#356]
As it was discovered while developing Ericsson/CodeCheckerEclipsePlugin#72, CodeChecker responses in plain-text error messages. Let's assume that the server lives but `javarunner` does NOT exist.

```
CodeChecker cmd results -p 1234 -n javarunner -o json
```

For future-proofing I think this interface should be redesigned. Thrift, if configured for JSON encoding, cannot handle a plaintext result which messes up long-running connections (such as that in Ericsson/CodeCheckerEclipsePlugin), a `json`-format request should return an appropriate result (excluding critical error conditions).

(cc @Xazax-hun @Locutus18)

**Comment by gyorb** [comment]
I agree that the output in case of error is not a valid json, but 'CodeChecker cmd' is not an API it is only a command line client to view results (an empty valid json could be returned).
The thrift API to get the results can be found [here](https://github.com/Ericsson/codechecker/blob/master/thrift_api/report_viewer_server.thrift). The Eclipse plugin should use the thrift API too to get/filter the results.
The generated thrift stubs will handle the transfer protocol which will remain json because the [javascript client stub](https://thrift.apache.org/tutorial/js) supports only that if I'm right.

**Comment by whisperity** [comment]
Understandable, it is a good suggestion for @Locutus18. As far as I know, the Eclipse plugin *does* use Thrift to communicate with the server, but for some reason, ends up in a `CONNECTION_ERROR` flood (see the referred merge request and issue in OP) if certain criteria is not met.

Though it, i.e. using a call to `CodeChecker cmd` to fetch whether the runname exists, is a quick-fix.

**Comment by gyorb** [comment]
Exception error handling should be done by all the clients.
It is possible that an [exception](https://github.com/Ericsson/codechecker/blob/36f3e4d830636323a47b96fa45c163568120d6fc/thrift_api/shared.thrift#L56-L59) will be thrown by the server through the [thrift API](https://github.com/Ericsson/codechecker/blob/36f3e4d830636323a47b96fa45c163568120d6fc/thrift_api/report_viewer_server.thrift) in case of error.

**Comment by whisperity** [comment]
Closing this issue, as this must be fixed deeper in the Eclipse plugin.

@Locutus18 `getRunData()` should be used via the Thrift API and not via the command-line invocation to check if `javarunner` exists on the server.
