### ISSUE TITLE
CodeChecker analyze --file does not work together with -i skipfile

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#3595]
The CodeChecker VSCodePlugin uses the --file parameter to analyze single files.
Large projects load in their configuration using the --config parameter and if there is a -i skipfile given in the config, CodeChecker analyze call drops an error.

Allow -i skipfile and --file <file> to be given together. The behaviour should be that the only those files are analyzed which are both allowed by the skipfile and the --file ... parameters.

**Comment by csordasmarton** [comment]
Let's assume we have the following directory structure:
```
|-a.cpp
|-b.cpp
|-c.cpp
|-vendor (3rd party libs)
  |-lib.h
  |-lib.cpp
```

My skip file looks like this:
```
-*/a.cpp
-*/vendor/*
```

My `--file` option is `lib.cpp`.

Now in the code we are creating a single skip file handler but in this case it will not work because of the following reasons:
 - If I skip based on the `--file` option first, I will show reports from `lib.cpp` which should be skipped based on the skip file.
 - If I skip based on the skip file first, I will analyze other files as well.

**Proposed solution**: using multiple skip file handlers. First I will skip based on the `--file` option AND narrow the results further based on the skip file.

**Important**: this behaviour also needs to be changed in the `CodeChecker parse` command.
