### ISSUE TITLE
Custom AST Provision

### ISSUE THREAD

**Issue by VenoVeno** [Ericsson/codechecker#3800]
**Is your feature request related to a problem? Please describe.**
Can CodeChecker capture issues without actually compiling the source files.
Can CodeChecker accept AST from user and parse results?

**Comment by VenoVeno** [comment]
> What is the motivation behind avoiding compilation?

As it is Static Code Analysis, why does it require compilation?

**Comment by bruntib** [comment]
Because Clang (that CodeChecker drives under the hood) is a compiler itself. It builds the abstract syntax tree (that's what I mean by compilation), builds the control flow graph and does the analysis based on these. Of course, it doesn't do any further build steps, like linking or creating executable, etc.

**Comment by bruntib** [comment]
One more thing is that clang doesn't compile the code in order to run it, so it is not a dynamic analysis. The compilation of the program (i.e. building the AST) fits in the terms of static analysis.

**Comment by VenoVeno** [comment]
If there is no compilation means, here generating AST. Is it possible to generate a partial AST.
Have a look at [this](https://stackoverflow.com/questions/74873856/clang-generate-ast-with-skipping-missing-type-and-missing-headers) SO Ques.

**Comment by bruntib** [comment]
Let me introduce some terms, so we can use the same meanings of these. When building a C/C++ program (with this command: `clang++ main.cpp` then many things happen: preprocessing, compilation, code optimization, linking, code generation, etc. Note, that I call these steps together as "building the program". Many times we're saying that "clang++ main.cpp" is the "compilation of the program", but I think this makes a confusion, because step 2 in the previous list is also named as "compilation" in the literature. And I think, the distinction is important here, and I use the word "compilation" in the terms of the 2nd phase of the build process. Sorry, if I talk too much, but I think, this is important here :)

So compilation is needed, because the AST is built in this step. This can't be done without having a declaration for every named entity (variables, functions, etc.) Since lacking a declaration for a used symbol is a syntax error, not having "windows.h" constitutes in a compiler error. I'm not sure if clang is capable to build a partial AST, but I don't know how a function's AST would look like if it doesn't know what the meaning of some symbols in it are.

I hope, I managed to answer your question, but if not, then let's continue the discussion.

**Comment by VenoVeno** [comment]
Hi, @bruntib. Thanks for your valuable answer. 
AST is part of Clang Front-end, they why does a compilation is needed?

The main reason i'm asking here is AST can be partial right?. PMD for Java will skip the missing classes and generate AST for the partial Java Source. I'm expecting a similar kind of behaviour. I know there is a lack of information, still i look it for. I'm not comparing PMD here with Clang. I know the fact that Clang is a compiler. Just asking if it would be possible. A got a solution similar to skip the missing headers. [link](https://stackoverflow.com/a/45239905/9645404). Adding to the fix, If i make the compiler to stop throwing missing errors, there may be definitions and missing functions. That's fine. I'm looking for a *PARTIAL CODE ANALYSIS*, instead of failing.

Just to know what i'm trying,
The reason why i go with partial AST is Clang doesn't have a full support for MSVC developed code. For some smaller piece of code, i faced with lot of errors as the code is not supported by clang and it is still compiled by MSVC (cl.exe). Issue [1](https://github.com/llvm/llvm-project/issues/59997), [2](https://github.com/llvm/llvm-project/issues/59955).

**Comment by bruntib** [comment]
Hi,
Now I understand the intentions, thank you. I'm not aware if Clang is able to build a partial AST, it is possible, though. If this can be done with some clang compiler flag, then we could wire it to the CodeChecker interface. As far as I see, you made some investigation in the topic already. If you manage to find the proper clang parameters that could be appended to the analyzer invocation, then please, share it.

**Comment by VenoVeno** [comment]
Thanks for your comment.
