### ISSUE TITLE
orphan checker name element in bug filter

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#422]
In Codechecker Run Overview, checker filter dropdown, there is an orphan elment "(1)"  under the Unspecified checkers list.

clicking on it, lists all results.

Reproducible by checking 3.1.2
http://md-mtas2.tsp.eth.ericsson.se:9997/#run=2

**Comment by bruntib** [comment]
Is there a reason why this issue is reopened?

**Comment by Xazax-hun** [comment]
Maybe I am mistaken, but the commit fixes the fact that there is no name displayed for a checker, but we still don't know whether the source of the error is a checker bug, plist parser bug or tidy output to plist converter bug.

**Comment by bruntib** [comment]
Yes, but the intention of this commit (and the issue) was to eliminate unnamed checkers from the GUI filter field, because it causes to select checkers of all checker types.
I agree that the root problem is that sometimes the checker name can't be resolved. Though I haven't implemented a checker yet, but it seems to me that the missing name is a checker specific issue, which has to be examined individually. We can never know if there will be a checker or even a new analyzer type tomorrow for which the checker names are not resolved, like it was the case when we used heuristics to find checker names to find out checker names from old format plists generated by old analyzers.

**Comment by Xazax-hun** [comment]
In case we are confident that this is a checker bug, I'm ok with closing this issue.

**Comment by bruntib** [comment]
I close this issue, because the problem has disappeared also at the provided URL. Maybe a fix has corrected it (like #429).
