### ISSUE TITLE
Suboptimal presentation of tidy results

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#461]
Show which checker found the error in quickcheck view if possible.
For clang sa the checker name is in the plist but until clang-tidy does not support some formatted output (plist) it is hard to find out the checker names based on the error messages.

**Comment by Xazax-hun** [comment]
The checker name is available in the output of tidy checks. So in case the name of tidy checks is not in the plist, it is the fault of the tidy output to plist converter.

**Comment by Xazax-hun** [comment]
Ok, I checked what is going on:
* The plist contains the name of the check even for tidy checks.
* The name of the check is not emitted.
* Clang Tidy fixits and notes are registered as events or steps in the static analyzer. This is suboptimal, see the next point.
* Clang Tidy fixits and notes are printed instead of the actual error message, because the last event is printed in quickcheck mode unless print steps is activated.

So in order to have proper reporting:
* Fixits and notes should be stored separately, not as events.
* The proper message should be displayed instead of fixits and notes.
* Fixits and notes should be only displayed if verbose output (e.g. steps, but it could be renamed) is turned on.
* The name of the check should be displayed.

**Comment by Xazax-hun** [comment]
Note that, the WebGUI should also behave diffenertly for notes, fixits and events.

**Comment by gyorb** [comment]
We can close this issue, every part of it was done.
