### ISSUE TITLE
building fails if stopped in the past

### ISSUE THREAD

**Issue by prazek** [Ericsson/codechecker#625]
Hi,
so when I hit ^C durring make package, running make package again didn't work.
It is possible that I did that when building dojotoolkit, because I saw later build complaining about it.
make clean also didn't help here, so something must be broken.

**Comment by whisperity** [comment]
If the make package is stopped initially when dependencies are being downloaded, this _might_ cause the problem, albeit right now I don't see the exact reason for it. What was the "complaining"?

To alleviate this issue, remove everything under `vendor` except `build-logger`... or simply do a fresh checkout again.

**Comment by prazek** [comment]
Tha'ts what I did, but I would consider it a bug in the build step - specialy that make clean didn't help.

**Comment by Xazax-hun** [comment]
Having clean removing the dependencies is not practical, because one would need to redownload them. I would add a dist-clean target, that would remove those dependencies as well. Furthermore, I think it would be possible to make the build script transactional. So in case ^C is hit during the download/install of a dependency, the build script could remove the directory of the half prepared dependency before terminating. This way the next run should restart with the missing dependencies instead of skipping a half downloaded one/prepared one.

**Comment by gyorb** [comment]
I think @prazek is right that clean should remove everything because that is what is expected, but I agree with @Xazax-hun too that it was not part of the clean because we need to wait for the download and during development it takes too much time.
I've introduced a `clean_package` target which will remove only the package and keep the vendor projects.
I'm not sure we should invest too much effort into the transactional packaging because we plan to create binary releases which will be easier to download and use.

**Comment by prazek** [comment]
As long as downloading will be ^C proof, then it seems resonable that make clean would not delete downloaded files. Other way is to have additional command to clean everything except downloaded files that you as developer would use, so that `make clean` would be intuitive to normal user.
