### ISSUE TITLE
WEBGUI: Convert Thrift API calls from syncronous to async calls

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#66]
when showing run overview the checker names that are active in the current run are loaded synchronously. this couses the web browser to hang when there are many thousand hits.

**Comment by bobszi** [comment]
Currently most of the Thrift API calls to CodeChecker server are syncronous, resulting in the "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience" warning.

All Thrift API calls should be converted to async calls to prevent hangs of the WEBGUI when waiting for response from the server.
