### ISSUE TITLE
Make server port mandatory in command line clients

### ISSUE THREAD

**Issue by bruntib** [Ericsson/codechecker#740]
When starting `CodeChecker check` command without a port provided to a running server then an error message returns which says that the API function at the server side is not found. This error may also occur for other client applications, but I haven't tried them yet. A proper error message should be given instead of the current one which now prints an unavailable API function name, or the server port should be mandatory.

**Comment by whisperity** [comment]
**Do NOT make `--port` mandatory, as it *works* in default settings!** It was made not mandatory in the initial pull request #717 so that `CodeChecker server` followed by `CodeChecker store` works without the user having to specify any parameters.

This happens if a valid Thrift server **already** runs on `localhost:8001` and listens, which is **NOT** a `CodeChecker server`. If the user starts `CodeChecker server `**--port 1234`** then `CodeChecker check `**--port 1234`** should be used too.

But I agree the error message should be made better to at least say _Something runs on `host:port` but it is not a CodeChecker server I can connect to._ And the native Thrift error could be printed in `DEBUG` loglevel.

**Comment by dkrupp** [comment]
there is no `--port` parameter anymore
