### ISSUE TITLE
Selecting multiple run tags

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#969]
There can be multiple run tags for one run `v1, v2`.
Does it make sense to select multiple tags in the filter for the same run?

It would list the results from `v1` and `v2`. In this case `v2` shouldn't be enough?
We do not delete results just mark them as fixed so `v2` should contain all the results from `v1`.

**Comment by csordasmarton** [comment]
I checked the filter condition:
```py
and_(Report.detected_at <= date, or_(Report.fixed_at.is_(None), Report.fixed_at >= date))
```
If the user selects `v2` the results will contain all the results from `v1`. I also tested it.

Otherwise, I think it would be another logic for the user if we do not list older tags and with the left hand side filter the user can changes to an older run tag easily now because we list all the tags.

**Comment by gyorb** [comment]
If it does not mess up the filtering and the filter will contain the results from `v2` tag (in this case)
than its ok to keep it as it is now, we do not need to introduce some extra logic.
