### ISSUE TITLE
check command fails with no report directory

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#992]
CodeChecker check -b make
works in the ~/.codechecker/reports directory.

It should clear contents of this default before it is run, otherwise it will print old results not belonging to this analysis (that remained in this directory from old analysis runs).

This clean up should only be done if no output report directory was specified, so that incremental analysis would work.

**Comment by bruntib** [comment]
I don't agree with handling the default output directory differently from the explicitly given output directory. That's why we have a `--force` flag.
Although it would be another question that `CodeChecker check` uses `--force` and `CodeChecker analyze` uses `--clean` for this behavior. We should consider unifying these.

**Comment by dkrupp** [comment]
if `-o` is not specified place the results under `/tmp` in a random named directory (UUID) which is removed, after the command has finished.
